version: 2.1

jobs:
  pull_request_comment_test:
    docker:
      - image: ghcr.io/cli/cli:latest
    steps:
      - checkout
      - run:
          name: Authenticate GitHub CLI
          command: |
            echo "${GITHUB_TOKEN}" | gh auth login --with-token
      - run:
          name: Post PR comment
          command: |
            gh pr comment $CIRCLE_PR_NUMBER --body "ビルド完了: ${CIRCLE_BUILD_URL}"
workflows:
  version: 2
  main:
    jobs:
      - pull_request_comment_test:
          filters:
            branches:
              only: /.*/
