version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0"  # 使用するXcodeのバージョンを指定

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: SlackにメッセージをPOSTする
          command: |
           curl -X POST \
           -H 'Content-type:application/json' \
           --data "{'text':'Hi!'}" ${SLACK_WEBHOOK}

workflows:
  version: 2
  main:
    jobs:
      - slack_test:
          context: SLACK_INTEGRATION
