version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0"  # 使用するXcodeのバージョンを指定

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: ステップで定義された環境変数を利用する
          environment:
            NODE_ENV: production
          command: echo "NODE_ENV is '$NODE_ENV'"
      - run:
          name: 環境変数は受け継がれない
          command: echo "NODE_ENV is '$NODE_ENV'"
