version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0"  # 使用するXcodeのバージョンを指定

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: ビルトイン環境変数の利用
          command: |
            echo "CI is '$CI'"
            echo "CIRCLE_SHA1 is '$CIRCLE_SHA1'"
            echo "CIRCLE_BRANCH is '$CIRCLE_BRANCH'"
