workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
        filters: # ワークフローを実行したいコミットタグやブランチを指定する際に使用
          tags:
            only: /.*/
      - deploy:
        requires:
          -build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

##commands: # stepsを共通化し、使いまわせるようにしたもの
##  sayhello:
##    description: "Say Hello"
##    parameters:
##      to:
##        type: string
##        default: "World"
##    steps:
##      - run: echo Hello << parameters.to >>

##jobs:
##  build:
##    docker:
##      - image: cimg/node:lts
##    steps:
##      - sayhello:
##          to: Everyone

## workflowを明示的に定義しない場合はデフォルトで以下のworkflowが適用される
## workflows:
##   version: 2.1
##   workflow:
##     jobs:
##       -build
