version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0"  # 使用するXcodeのバージョンを指定

commands:
  sayhello:
    description: "Say Hello"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run:
          name: Say Hello
          command: echo Hello << parameters.to >>

jobs:
  build:
    executor: macos-executor
    steps:
      - sayhello:
          to: Everyone

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
