version: 2.1

executors: # jobの実行環境を共通化し、使いまわせるようにしたもの
  macos-executor:
    macos:
      xcode: "15.2.0"  # 使用するXcodeのバージョンを指定

jobs:
  build:
    executor: macos-executor
    steps:
      - run: echo "hello world"

## workflowを明示的に定義しない場合はデフォルトで以下のworkflowが適用される
## workflows:
##   version: 2.1
##   workflow:
##     jobs:
##       -build
