version: 2.1
      
commands: # stepsを共通化し、使いまわせるようにしたもの
  sayhello:
    steps:
      - run: echo "hello world"

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - sayhello

## workflowを明示的に定義しない場合はデフォルトで以下のworkflowが適用される
## workflows:
##   version: 2.1
##   workflow:
##     jobs:
##       -build
