version: 2.1

jobs:
  pull_request_comment_test:
    docker:
      - image: cimg/ruby:2.6  # Ruby 2.6 のイメージを使用
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install ghi
      - run:
          name: Post PR comment
          command: |
            ghi pr comment ${PR_ID} "Githubプルリクエストにコメント ${CIRCLE_BUILD_URL}"
workflows:
  version: 2
  main:
    jobs:
      - pull_request_comment_test:
          filters:
            branches:
              only: /.*/
